from .cpu._onnx2py import (
    DeviceConfigurationProto,
    DataType,
    IntIntListEntryProto,
    Message,
    NodeDeviceConfigurationProto,
    OperatorSetIdProto,
    OperatorStatus,
    ShardedDimProto,
    ShardingSpecProto,
    SimpleShardedDimProto,
    SparseTensorProto,
    StringStringEntryProto,
    TensorAnnotation,
    TensorProto,
    TensorShapeProto,
    TypeProto,
)
